# Generated by Django 5.1.4 on 2025-02-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
