# Generated by Django 5.1.4 on 2025-02-13 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=255, unique=True)),
                ('ar_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='government',
            options={'ordering': ['name'], 'verbose_name': 'حكومة', 'verbose_name_plural': 'الحكومات'},
        ),
        migrations.AlterField(
            model_name='formplus',
            name='date',
            field=models.DateField(blank=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='formplus',
            name='government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.government', verbose_name='الحكومة'),
        ),
        migrations.AlterField(
            model_name='formplus',
            name='keywords',
            field=models.TextField(blank=True, max_length=999, verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='formplus',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم'),
        ),
        migrations.AlterField(
            model_name='formplus',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
    ]
