# Generated by Django 5.1.4 on 2025-02-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_publication_remove_incoming_dept_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='company',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='number_applied',
        ),
        migrations.AddField(
            model_name='publication',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='مخفي'),
        ),
        migrations.AddField(
            model_name='publication',
            name='owner',
            field=models.CharField(default=1, max_length=255, verbose_name='مالك العلامة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='applicant',
            field=models.CharField(max_length=255, verbose_name='طالب التسجيل'),
        ),
    ]
