# Generated by Django 5.1.4 on 2025-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_comtype_country_doctype_alter_government_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comtype',
            options={'verbose_name': 'نوع شركة', 'verbose_name_plural': 'انواع الشركات'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'دولة', 'verbose_name_plural': 'الدول'},
        ),
        migrations.AlterModelOptions(
            name='doctype',
            options={'verbose_name': 'نوع مستند', 'verbose_name_plural': 'انواع المستندات'},
        ),
        migrations.AlterModelOptions(
            name='government',
            options={'verbose_name': 'حكومة', 'verbose_name_plural': 'الحكومات'},
        ),
        migrations.AlterField(
            model_name='comtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ar_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='country',
            name='en_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم بالانجليزية'),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='government',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
    ]
