# Generated by Django 5.1.4 on 2025-02-13 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_comtype_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objection',
            name='complain_number',
        ),
        migrations.AddField(
            model_name='objection',
            name='pub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='documents.publication', verbose_name='الاشهار'),
            preserve_default=False,
        ),
    ]
