# Generated by Django 5.1.4 on 2025-02-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_objection_complain_number_objection_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='unique_code',
            field=models.CharField(default=1, editable=False, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
