# Generated by Django 5.1.4 on 2025-02-07 10:54

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_publication_decree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='img_file',
            field=models.ImageField(blank=True, upload_to=documents.models.get_img_upload_path, verbose_name='الصورة'),
        ),
    ]
