# Generated by Django 5.1.4 on 2025-02-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_objection_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='number',
            field=models.IntegerField(default=1, verbose_name='رقم المعارضة'),
            preserve_default=False,
        ),
    ]
