# Generated by Django 5.1.4 on 2025-02-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_publication_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='e_number',
            field=models.CharField(max_length=10, verbose_name='رقم النشرية'),
        ),
    ]
