# Generated by Django 5.1.4 on 2025-02-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_publication_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
