# Generated by Django 5.1.4 on 2025-02-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_objection_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='رقم المعارضة'),
        ),
    ]
