# Generated by Django 5.1.4 on 2025-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_objection_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecreeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='رقم الفئة')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الفئة')),
            ],
            options={
                'verbose_name': 'الفئة',
                'verbose_name_plural': 'الفئات',
            },
        ),
    ]
