# Generated by Django 5.1.4 on 2025-02-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='decree',
            name='objection_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاعتراض'),
        ),
    ]
