# Generated by Django 5.1.4 on 2025-02-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_objection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('initial', 'نشر مبدئي'), ('conflict', 'متنازع عليه'), ('final', 'نشر نهائي')], max_length=50, verbose_name='حالة التسجيل'),
        ),
    ]
