# Generated by Django 5.1.4 on 2025-02-11 16:31

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_publication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='decree',
            name='published',
            field=models.BooleanField(default=False, verbose_name='تم نشره'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(default=documents.models.default_created_at, verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='e_number',
            field=models.IntegerField(max_length=10, verbose_name='رقم النشرية'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.IntegerField(max_length=10, verbose_name='رقم التسجيل'),
        ),
    ]
