# Generated by Django 5.1.4 on 2025-02-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_decree_published_alter_publication_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='e_number',
            field=models.IntegerField(verbose_name='رقم النشرية'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.IntegerField(verbose_name='رقم التسجيل'),
        ),
    ]
