# Generated by Django 5.1.4 on 2025-02-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_publication_e_number_alter_publication_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='decree',
            field=models.IntegerField(verbose_name='رقم القرار'),
        ),
    ]
