# Generated by Django 5.1.4 on 2025-02-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_publication_decree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decree',
            old_name='published',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='decree',
            name='category',
            field=models.IntegerField(blank=True, max_length=255, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='number',
            field=models.IntegerField(max_length=10, verbose_name='رقم القرار'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='number_applied',
            field=models.IntegerField(max_length=10, verbose_name='رقم القيد'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.IntegerField(blank=True, max_length=255, verbose_name='الفئة'),
        ),
    ]
