# Generated by Django 5.1.4 on 2025-02-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_rename_published_decree_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decree',
            name='category',
            field=models.IntegerField(blank=True, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='number',
            field=models.IntegerField(verbose_name='رقم القرار'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='number_applied',
            field=models.IntegerField(verbose_name='رقم القيد'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.IntegerField(blank=True, verbose_name='الفئة'),
        ),
    ]
