# Generated by Django 5.1.4 on 2025-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_decree_category_alter_decree_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decree',
            name='objection_date',
        ),
        migrations.AddField(
            model_name='objection',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تم دفع الرسوم'),
        ),
        migrations.AddField(
            model_name='objection',
            name='status',
            field=models.CharField(choices=[('accepted', 'موافقة'), ('rejected', 'رفض'), ('suspended', 'معلق')], default=2, max_length=50, verbose_name='حالة الاعتراض'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='is_objected',
            field=models.BooleanField(default=False, verbose_name='تم الاعتراض عليه'),
        ),
        migrations.AddField(
            model_name='publication',
            name='objection_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاعتراض'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='تم اشهاره مبدئيا'),
        ),
    ]
