# Generated by Django 5.1.4 on 2025-02-12 09:13

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_remove_decree_objection_date_objection_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField(blank=True, max_length=999)),
                ('pdf_file', models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='objection',
            name='phone',
            field=models.CharField(default=1, max_length=10, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objection',
            name='reason',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسباب الرفض'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('accepted', 'موافقة'), ('rejected', 'رفض')], max_length=50, verbose_name='حالة الاعتراض'),
        ),
    ]
